# Changes here will be overwritten by Copier
_commit: 9dfa165
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
email: t.paine154@gmail.com
github: airflow-laminar
project_description: Common operators and tasks for airflow
project_name: airflow-common-operators
python_version_primary: '3.11'
team: the airflow-common-operators authors
